# Generated by Django 4.1.7 on 2023-03-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('keywords', models.TextField()),
                ('skill_level', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
