# Generated by Django 4.1.7 on 2023-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='duration',
            field=models.IntegerField(default=3),
        ),
    ]
