# Generated by Django 4.1.7 on 2023-03-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_workshop_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
