# Generated by Django 4.1.7 on 2023-03-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_basicarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitch', models.TextField()),
                ('skill_level', models.TextField(choices=[('Beginner', 'One'), ('Intermediate', 'Two'), ('Advanced', 'Three')])),
                ('description', models.TextField()),
                ('image', models.ImageField(default='https://images.pexels.com/photos/6843263/pexels-photo-6843263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='basicarticle',
            name='image',
            field=models.ImageField(default='https://images.pexels.com/photos/8971902/pexels-photo-8971902.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', upload_to=''),
        ),
    ]
