# Generated by Django 4.1.7 on 2023-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_bio_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='sheep.jpg', upload_to='profile_images/'),
        ),
    ]
